export { default as logoSvg } from "./kolo-logo.svg";
export { default as searchSvg } from "./search-icon.svg";
export { default as filterSvg } from "./filter-icon.svg";
export { default as cabrioletSvg } from "./cabriolet-icon.svg";
export { default as coupeSvg } from "./coupe-icon.svg";
export { default as fuelSvg } from "./gas-icon.svg";
export { default as hatchbackSvg } from "./hatchback-icon.svg";
export { default as seatSvg } from "./seat-icon.svg";
export { default as sedanSvg } from "./sedan-icon.svg";
export { default as suvSvg } from "./suv-icon.svg";
export { default as transmissionSvg } from "./transmission-icon.svg";
export { default as coupe } from "./coupe.svg";
export { default as cabriolet } from "./cabriolet.svg";
export { default as hatchback } from "./hatchback.svg";
export { default as sedan } from "./sedan.svg";
export { default as suv } from "./suv.svg";
export { default as notifSvg } from "./notification-icon.svg";
export { default as desert1Svg } from "./oldWheel.svg";
export { default as wheelSvg } from "./Layer_1.svg";
export { default as desert2Svg } from "./Group.svg";
export { default as faceSvg } from "./faceSvg.svg";
export { default as instagramSvg } from "./instagramSvg.svg";
export { default as tikTokSvg } from "./tikTokSvg.svg";
export { default as lineSvg } from "./Rectangle 68.svg";
export { default as koloFooterSvg } from "./koloFooter.svg";
export { default as fallbackImageSvg } from "./fallbackImage.svg";
export { default as pencilSvg } from "./pencil.svg";
export { default as profileLogo } from "./Vector (2).svg";
export { default as profileWhiteLogo } from "./profile.svg";
export { default as roadSvg } from "./road.svg";
export { default as car } from "./car.svg";
export { default as map } from "./map.svg";
export { default as neanderthal } from "./neandertalac.svg";
export { default as path } from "./path.svg";
export { default as neanderthalKolo } from "./kolo neandertalac.svg";
